import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ pokemon }) {
  console.log(pokemon);
  return (
    <>
      <Head>
        <title>Pokemon Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ textAlign: "center", marginBottom: "20px" }}>Pokemon's</h1>
      <div
        style={{
          border: "1px solid red",
          display: "grid",
          gridTemplateColumns: "repeat(3,1fr)",
        }}
      >
        {pokemon.map((el) => (
          <div
            key={el.id}
            style={{
              border: "1px solid teal",
              padding: "20px",
              textAlign: "center",
            }}
          >
            <Link href={`/singlePokemonPage/${el.id}`}>
              <img src={el.img_url} alt="error" />
              <p>{el.number}</p>
              <h2>{el.name}</h2>
              <div style={{ padding: "10px" }}>
                <button
                  style={{
                    backgroundColor: "teal",
                    border: "none",
                    color: "white",
                    textAlign: "center",
                    padding: "10px 15px",
                    textDecoration: "none",
                    display: "inline-block",
                    fontSize: "15px",
                  }}
                >
                  {el.type}
                </button>
                <button
                  style={{
                    backgroundColor: "blue",
                    border: "none",
                    color: "white",
                    textAlign: "center",
                    padding: "10px 15px",
                    textDecoration: "none",
                    display: "inline-block",
                    fontSize: "15px",
                  }}
                >
                  {el.version}
                </button>
              </div>
            </Link>
          </div>
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://fluffy-tick-dirndl.cyclic.app/pokemon");
  const data = await response.json();
  console.log("response", data);
  return {
    props: {
      pokemon: data,
    },
  };
}
